import type {Metadata} from "next";

import {Suspense} from "react";

import "../globals.css";

export const metadata: Metadata = {
  title: "blocking-ssr-demo",
  description: "Generated by appncy",
};

export default async function RootLayout({children}: {children: React.ReactNode}) {
  return <Suspense>{children}</Suspense>;
}
